# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6 #continuumio/miniconda3
      
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/VNI
    steps:
      - checkout
      
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
        #mkdir .kaggle
            #cd .kaggle
            #echo "{"username":\"${KAGGLE_NAME}\","key":\"${KAGGLE_KEY}\}" > kaggle.json
            #cd ..
            # kaggle competitions download titanic
            #jupyter-nbconvert --execute kernel.ipynb
            #kaggle competitions submit titanic -f submission.csv
    
      # https://pytest.org
      # https://nose.readthedocs.io
      #mkdir -p reports
      #jupyter nbconvert --execute task_0.ipynb
      #mv task_0.html reports/task.html
      - run:
          name: downloading and commiting kernel
          command: |
            . venv/bin/activate
            mkdir .kaggle
            cd .kaggle
            echo "{"username":\"${KAGGLE_USERNAME}\","key":\"${KAGGLE_KEY}\}" > kaggle.json
            cd ..
            kaggle competitions download titanic
            jupyter-nbconvert --execute kernel.ipynb
            kaggle competitions submit titanic -f submission.csv -m "My submission"
            mkdir reports
            mv kernel.html reports/

      - store_artifacts:
          path: reports
          destination: reports
